#PROBLEM #1
#USING THE TRY/EXCEPT FUNCTIONALITY OF PYTHON TO CATCH AN ERROR
try:
    for i in ["a","b","c"]:
        print(i**2)
except:
    print("Error in performing i^2 function!")
